/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthMagicLinkRouteImport } from './routes/auth/magic-link'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth/accept-invite'
import { Route as AppUsersRouteImport } from './routes/app/users'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppRolesRouteImport } from './routes/app/roles'
import { Route as AppPermissionsRouteImport } from './routes/app/permissions'
import { Route as AppEntitiesRouteImport } from './routes/app/entities'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppApiKeysRouteImport } from './routes/app/api-keys'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppUsersIndexRouteImport } from './routes/app/users.index'
import { Route as AppRolesIndexRouteImport } from './routes/app/roles.index'
import { Route as AppPermissionsIndexRouteImport } from './routes/app/permissions.index'
import { Route as AppEntitiesIndexRouteImport } from './routes/app/entities.index'
import { Route as AppUsersApiKeysRouteImport } from './routes/app/users.api-keys'
import { Route as AppUsersUserIdRouteImport } from './routes/app/users.$userId'
import { Route as AppRolesRoleIdRouteImport } from './routes/app/roles.$roleId'
import { Route as AppPermissionsPermissionIdRouteImport } from './routes/app/permissions.$permissionId'
import { Route as AppEntitiesEntityIdRouteImport } from './routes/app/entities.$entityId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppEntitiesRoute = AppEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRolesRoute,
} as any)
const AppPermissionsIndexRoute = AppPermissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPermissionsRoute,
} as any)
const AppEntitiesIndexRoute = AppEntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEntitiesRoute,
} as any)
const AppUsersApiKeysRoute = AppUsersApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppRolesRoleIdRoute = AppRolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => AppRolesRoute,
} as any)
const AppPermissionsPermissionIdRoute =
  AppPermissionsPermissionIdRouteImport.update({
    id: '/$permissionId',
    path: '/$permissionId',
    getParentRoute: () => AppPermissionsRoute,
  } as any)
const AppEntitiesEntityIdRoute = AppEntitiesEntityIdRouteImport.update({
  id: '/$entityId',
  path: '/$entityId',
  getParentRoute: () => AppEntitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/entities': typeof AppEntitiesRouteWithChildren
  '/app/permissions': typeof AppPermissionsRouteWithChildren
  '/app/roles': typeof AppRolesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/entities/$entityId': typeof AppEntitiesEntityIdRoute
  '/app/permissions/$permissionId': typeof AppPermissionsPermissionIdRoute
  '/app/roles/$roleId': typeof AppRolesRoleIdRoute
  '/app/users/$userId': typeof AppUsersUserIdRoute
  '/app/users/api-keys': typeof AppUsersApiKeysRoute
  '/app/entities/': typeof AppEntitiesIndexRoute
  '/app/permissions/': typeof AppPermissionsIndexRoute
  '/app/roles/': typeof AppRolesIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/entities/$entityId': typeof AppEntitiesEntityIdRoute
  '/app/permissions/$permissionId': typeof AppPermissionsPermissionIdRoute
  '/app/roles/$roleId': typeof AppRolesRoleIdRoute
  '/app/users/$userId': typeof AppUsersUserIdRoute
  '/app/users/api-keys': typeof AppUsersApiKeysRoute
  '/app/entities': typeof AppEntitiesIndexRoute
  '/app/permissions': typeof AppPermissionsIndexRoute
  '/app/roles': typeof AppRolesIndexRoute
  '/app/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/entities': typeof AppEntitiesRouteWithChildren
  '/app/permissions': typeof AppPermissionsRouteWithChildren
  '/app/roles': typeof AppRolesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/entities/$entityId': typeof AppEntitiesEntityIdRoute
  '/app/permissions/$permissionId': typeof AppPermissionsPermissionIdRoute
  '/app/roles/$roleId': typeof AppRolesRoleIdRoute
  '/app/users/$userId': typeof AppUsersUserIdRoute
  '/app/users/api-keys': typeof AppUsersApiKeysRoute
  '/app/entities/': typeof AppEntitiesIndexRoute
  '/app/permissions/': typeof AppPermissionsIndexRoute
  '/app/roles/': typeof AppRolesIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/account'
    | '/app/api-keys'
    | '/app/dashboard'
    | '/app/entities'
    | '/app/permissions'
    | '/app/roles'
    | '/app/settings'
    | '/app/users'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/magic-link'
    | '/auth/reset-password'
    | '/app/entities/$entityId'
    | '/app/permissions/$permissionId'
    | '/app/roles/$roleId'
    | '/app/users/$userId'
    | '/app/users/api-keys'
    | '/app/entities/'
    | '/app/permissions/'
    | '/app/roles/'
    | '/app/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/account'
    | '/app/api-keys'
    | '/app/dashboard'
    | '/app/settings'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/magic-link'
    | '/auth/reset-password'
    | '/app/entities/$entityId'
    | '/app/permissions/$permissionId'
    | '/app/roles/$roleId'
    | '/app/users/$userId'
    | '/app/users/api-keys'
    | '/app/entities'
    | '/app/permissions'
    | '/app/roles'
    | '/app/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/account'
    | '/app/api-keys'
    | '/app/dashboard'
    | '/app/entities'
    | '/app/permissions'
    | '/app/roles'
    | '/app/settings'
    | '/app/users'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/magic-link'
    | '/auth/reset-password'
    | '/app/entities/$entityId'
    | '/app/permissions/$permissionId'
    | '/app/roles/$roleId'
    | '/app/users/$userId'
    | '/app/users/api-keys'
    | '/app/entities/'
    | '/app/permissions/'
    | '/app/roles/'
    | '/app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/permissions': {
      id: '/app/permissions'
      path: '/permissions'
      fullPath: '/app/permissions'
      preLoaderRoute: typeof AppPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entities': {
      id: '/app/entities'
      path: '/entities'
      fullPath: '/app/entities'
      preLoaderRoute: typeof AppEntitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/app/roles/': {
      id: '/app/roles/'
      path: '/'
      fullPath: '/app/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRolesRoute
    }
    '/app/permissions/': {
      id: '/app/permissions/'
      path: '/'
      fullPath: '/app/permissions/'
      preLoaderRoute: typeof AppPermissionsIndexRouteImport
      parentRoute: typeof AppPermissionsRoute
    }
    '/app/entities/': {
      id: '/app/entities/'
      path: '/'
      fullPath: '/app/entities/'
      preLoaderRoute: typeof AppEntitiesIndexRouteImport
      parentRoute: typeof AppEntitiesRoute
    }
    '/app/users/api-keys': {
      id: '/app/users/api-keys'
      path: '/api-keys'
      fullPath: '/app/users/api-keys'
      preLoaderRoute: typeof AppUsersApiKeysRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/app/users/$userId': {
      id: '/app/users/$userId'
      path: '/$userId'
      fullPath: '/app/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/app/roles/$roleId': {
      id: '/app/roles/$roleId'
      path: '/$roleId'
      fullPath: '/app/roles/$roleId'
      preLoaderRoute: typeof AppRolesRoleIdRouteImport
      parentRoute: typeof AppRolesRoute
    }
    '/app/permissions/$permissionId': {
      id: '/app/permissions/$permissionId'
      path: '/$permissionId'
      fullPath: '/app/permissions/$permissionId'
      preLoaderRoute: typeof AppPermissionsPermissionIdRouteImport
      parentRoute: typeof AppPermissionsRoute
    }
    '/app/entities/$entityId': {
      id: '/app/entities/$entityId'
      path: '/$entityId'
      fullPath: '/app/entities/$entityId'
      preLoaderRoute: typeof AppEntitiesEntityIdRouteImport
      parentRoute: typeof AppEntitiesRoute
    }
  }
}

interface AppEntitiesRouteChildren {
  AppEntitiesEntityIdRoute: typeof AppEntitiesEntityIdRoute
  AppEntitiesIndexRoute: typeof AppEntitiesIndexRoute
}

const AppEntitiesRouteChildren: AppEntitiesRouteChildren = {
  AppEntitiesEntityIdRoute: AppEntitiesEntityIdRoute,
  AppEntitiesIndexRoute: AppEntitiesIndexRoute,
}

const AppEntitiesRouteWithChildren = AppEntitiesRoute._addFileChildren(
  AppEntitiesRouteChildren,
)

interface AppPermissionsRouteChildren {
  AppPermissionsPermissionIdRoute: typeof AppPermissionsPermissionIdRoute
  AppPermissionsIndexRoute: typeof AppPermissionsIndexRoute
}

const AppPermissionsRouteChildren: AppPermissionsRouteChildren = {
  AppPermissionsPermissionIdRoute: AppPermissionsPermissionIdRoute,
  AppPermissionsIndexRoute: AppPermissionsIndexRoute,
}

const AppPermissionsRouteWithChildren = AppPermissionsRoute._addFileChildren(
  AppPermissionsRouteChildren,
)

interface AppRolesRouteChildren {
  AppRolesRoleIdRoute: typeof AppRolesRoleIdRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
}

const AppRolesRouteChildren: AppRolesRouteChildren = {
  AppRolesRoleIdRoute: AppRolesRoleIdRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
}

const AppRolesRouteWithChildren = AppRolesRoute._addFileChildren(
  AppRolesRouteChildren,
)

interface AppUsersRouteChildren {
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersApiKeysRoute: typeof AppUsersApiKeysRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersApiKeysRoute: AppUsersApiKeysRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEntitiesRoute: typeof AppEntitiesRouteWithChildren
  AppPermissionsRoute: typeof AppPermissionsRouteWithChildren
  AppRolesRoute: typeof AppRolesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEntitiesRoute: AppEntitiesRouteWithChildren,
  AppPermissionsRoute: AppPermissionsRouteWithChildren,
  AppRolesRoute: AppRolesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
